clone_depth: 5
environment:
  nodejs_version: "12"
platform: x64 # flow needs 64b platforms

branches:
  only:
    - main
    - production

# Install scripts. (runs after repo cloning)
install:
  # 1. Select the right node
  - ps: Install-Product node $env:nodejs_version $env:platform
  # 2. Setup the project
  - yarn install --frozen-lockfile

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - yarn versions
  # run tests
  - yarn test-all:ci
  - yarn build-prod:quiet

cache:
  - node_modules

# Don't actually build.
build: off
